language: node_js
node_js:
    - "8.16.0"
    - "10"
dist: trusty
addons:
  apt:
    packages:
      # This is required to run puppeteer (chrome) on linux/trusty
      - libnss3
      # for screenshot comparison
      - graphicsmagick
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn
before_script:
  - 'if [ "$NODE6" = "true" ]; then npm build --cwd node_modules/puppeteer; fi'
script:
  - yarn test-all
